export const RESERVATIONS_LIST_REQUEST = "RESERVATIONS_LIST_REQUEST";
export const RESERVATIONS_LIST_SUCCESS = "RESERVATIONS_LIST_SUCCESS";
export const RESERVATIONS_LIST_FAIL = "RESERVATIONS_LIST_FAIL";

export const RESERVATIONS_CREATE_REQUEST = "RESERVATIONS_CREATE_REQUEST";
export const RESERVATIONS_CREATE_SUCCESS = "RESERVATIONS_CREATE_SUCCESS";
export const RESERVATIONS_CREATE_FAIL = "RESERVATIONS_CREATE_FAIL";

export const RESERVATIONS_UPDATE_REQUEST = "RESERVATIONS_UPDATE_REQUEST";
export const RESERVATIONS_UPDATE_SUCCESS = "RESERVATIONS_UPDATE_SUCCESS";
export const RESERVATIONS_UPDATE_FAIL = "RESERVATIONS_UPDATE_FAIL";

export const RESERVATIONS_DELETE_REQUEST = "RESERVATIONS_DELETE_REQUEST";
export const RESERVATIONS_DELETE_SUCCESS = "RESERVATIONS_DELETE_SUCCESS";
export const RESERVATIONS_DELETE_FAIL = "RESERVATIONS_DELETE_FAIL";
